DROP TABLE IF EXISTS Developer;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS Languages;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Api;

CREATE TABLE Developer
	(d_id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	d_firstName VARCHAR(64) NOT NULL,
	d_lastName VARCHAR(64) NOT NULL,
	d_email VARCHAR(64) NOT NULL,
	d_passhash VARCHAR(64) NOT NULL,
	d_profileSetup BOOLEAN NOT NULL,
	d_projectAffil VARCHAR(64) NOT NULL,
	d_languages VARCHAR(64) NOT NULL,
	d_api VARCHAR(64) NOT NULL,
	d_category VARCHAR(64) NOT NULL,
	);

CREATE TABLE Project
	(p_id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	p_name VARCHAR(100) NOT NULL,
	s_class CHAR(2) NOT NULL,
	s_advfid INTEGER UNSIGNED NOT NULL
	);

CREATE TABLE Languages
	(s_id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	s_name VARCHAR(100) NOT NULL,
	s_class CHAR(2) NOT NULL,
	s_advfid INTEGER UNSIGNED NOT NULL
	);
	
CREATE TABLE Categories
	(s_id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	s_name VARCHAR(100) NOT NULL,
	s_class CHAR(2) NOT NULL,
	s_advfid INTEGER UNSIGNED NOT NULL
	);
	
CREATE TABLE Api
	(s_id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	s_name VARCHAR(100) NOT NULL,
	s_class CHAR(2) NOT NULL,
	s_advfid INTEGER UNSIGNED NOT NULL
	);
